import type { Metadata } from 'next'
import { Space_Mono } from 'next/font/google'
import './globals.css'

const space_mono = Space_Mono({
  weight : ['400','700']
  , subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'tip-calculator-app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={space_mono.className}>{children}</body>
    </html>
  )
}
